services:
  objectweaver:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "2008:2008"
    environment:
      PASSWORD: ${PASSWORD}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      ITEMS_MODEL: ${ITEMS_MODEL}
      VERBOSE_LOGS: ${VERBOSE_LOGS}
      LOCAL_API_KEY: ${LOCAL_API_KEY}
      LOCAL_API_URL: ${LOCAL_API_URL}
      GEMINI_API_KEY: ${GEMINI_API_KEY}

      LLM_PROVIDER: ${LLM_PROVIDER}
      LLM_API_URL: ${LLM_API_URL}
      LLM_API_KEY: ${LLM_API_KEY}
      LLM_MAX_TOKENS_PER_MINUTE: ${LLM_MAX_TOKENS_PER_MINUTE}
      LLM_MAX_REQUESTS_PER_MINUTE: ${LLM_MAX_REQUESTS_PER_MINUTE}
      LLM_BACKOFF_STRATEGY: ${LLM_BACKOFF_STRATEGY}
      LLM_USE_GZIP: ${LLM_USE_GZIP}
      LLM_ENABLE_BATCH: ${LLM_ENABLE_BATCH}
      LLM_BATCH_PRIORITY_THRESHOLD: ${LLM_BATCH_PRIORITY_THRESHOLD}
      KMEAN_EMBEDDING_MODEL: ${KMEAN_EMBEDDING_MODEL}
      KMEAN_AS_JUDGE: ${KMEAN_AS_JUDGE}
      
      
      ENVIRONMENT: ${ENVIRONMENT}
      GRPC_UNSECURE: ${GRPC_UNSECURE}
      CERT_FILE: ${CERT_FILE}
      KEY_FILE: ${KEY_FILE}
    networks:
      - monitoring

networks:
  monitoring:

volumes:
  grafana-storage:

