// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: objectweaver.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Definition message
type Definition struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Type            string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Instruction     string                 `protobuf:"bytes,2,opt,name=instruction,proto3" json:"instruction,omitempty"`
	Properties      map[string]*Definition `protobuf:"bytes,3,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Items           *Definition            `protobuf:"bytes,4,opt,name=items,proto3" json:"items,omitempty"`
	Model           string                 `protobuf:"bytes,5,opt,name=model,proto3" json:"model,omitempty"`
	ProcessingOrder []string               `protobuf:"bytes,6,rep,name=processingOrder,proto3" json:"processingOrder,omitempty"`
	SystemPrompt    string                 `protobuf:"bytes,7,opt,name=systemPrompt,proto3" json:"systemPrompt,omitempty"`
	HashMap         *HashMap               `protobuf:"bytes,8,opt,name=hashMap,proto3" json:"hashMap,omitempty"`
	TextToSpeech    *TextToSpeech          `protobuf:"bytes,9,opt,name=textToSpeech,proto3" json:"textToSpeech,omitempty"`
	SpeechToText    *SpeechToText          `protobuf:"bytes,10,opt,name=speechToText,proto3" json:"speechToText,omitempty"`
	Image           *Image                 `protobuf:"bytes,11,opt,name=image,proto3" json:"image,omitempty"`
	Req             *RequestFormat         `protobuf:"bytes,12,opt,name=req,proto3" json:"req,omitempty"`
	NarrowFocus     *Focus                 `protobuf:"bytes,13,opt,name=narrowFocus,proto3" json:"narrowFocus,omitempty"`
	SelectFields    []string               `protobuf:"bytes,14,rep,name=selectFields,proto3" json:"selectFields,omitempty"`
	SendImage       *SendImage             `protobuf:"bytes,15,opt,name=sendImage,proto3" json:"sendImage,omitempty"`
	Stream          bool                   `protobuf:"varint,16,opt,name=stream,proto3" json:"stream,omitempty"`
	OverridePrompt  string                 `protobuf:"bytes,17,opt,name=overridePrompt,proto3" json:"overridePrompt,omitempty"`
	Priority        int32                  `protobuf:"varint,18,opt,name=priority,proto3" json:"priority,omitempty"`
	DecisionPoint   *DecisionPoint         `protobuf:"bytes,19,opt,name=decisionPoint,proto3" json:"decisionPoint,omitempty"`
	ScoringCriteria *ScoringCriteria       `protobuf:"bytes,20,opt,name=scoringCriteria,proto3" json:"scoringCriteria,omitempty"`
	RecursiveLoop   *RecursiveLoop         `protobuf:"bytes,21,opt,name=recursiveLoop,proto3" json:"recursiveLoop,omitempty"`
	Epistemic       *EpistemicValidation   `protobuf:"bytes,22,opt,name=epistemic,proto3" json:"epistemic,omitempty"`
	ModelConfig     *ModelConfig           `protobuf:"bytes,23,opt,name=modelConfig,proto3" json:"modelConfig,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Definition) Reset() {
	*x = Definition{}
	mi := &file_objectweaver_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Definition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Definition) ProtoMessage() {}

func (x *Definition) ProtoReflect() protoreflect.Message {
	mi := &file_objectweaver_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Definition.ProtoReflect.Descriptor instead.
func (*Definition) Descriptor() ([]byte, []int) {
	return file_objectweaver_proto_rawDescGZIP(), []int{0}
}

func (x *Definition) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Definition) GetInstruction() string {
	if x != nil {
		return x.Instruction
	}
	return ""
}

func (x *Definition) GetProperties() map[string]*Definition {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *Definition) GetItems() *Definition {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *Definition) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Definition) GetProcessingOrder() []string {
	if x != nil {
		return x.ProcessingOrder
	}
	return nil
}

func (x *Definition) GetSystemPrompt() string {
	if x != nil {
		return x.SystemPrompt
	}
	return ""
}

func (x *Definition) GetHashMap() *HashMap {
	if x != nil {
		return x.HashMap
	}
	return nil
}

func (x *Definition) GetTextToSpeech() *TextToSpeech {
	if x != nil {
		return x.TextToSpeech
	}
	return nil
}

func (x *Definition) GetSpeechToText() *SpeechToText {
	if x != nil {
		return x.SpeechToText
	}
	return nil
}

func (x *Definition) GetImage() *Image {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *Definition) GetReq() *RequestFormat {
	if x != nil {
		return x.Req
	}
	return nil
}

func (x *Definition) GetNarrowFocus() *Focus {
	if x != nil {
		return x.NarrowFocus
	}
	return nil
}

func (x *Definition) GetSelectFields() []string {
	if x != nil {
		return x.SelectFields
	}
	return nil
}

func (x *Definition) GetSendImage() *SendImage {
	if x != nil {
		return x.SendImage
	}
	return nil
}

func (x *Definition) GetStream() bool {
	if x != nil {
		return x.Stream
	}
	return false
}

func (x *Definition) GetOverridePrompt() string {
	if x != nil {
		return x.OverridePrompt
	}
	return ""
}

func (x *Definition) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *Definition) GetDecisionPoint() *DecisionPoint {
	if x != nil {
		return x.DecisionPoint
	}
	return nil
}

func (x *Definition) GetScoringCriteria() *ScoringCriteria {
	if x != nil {
		return x.ScoringCriteria
	}
	return nil
}

func (x *Definition) GetRecursiveLoop() *RecursiveLoop {
	if x != nil {
		return x.RecursiveLoop
	}
	return nil
}

func (x *Definition) GetEpistemic() *EpistemicValidation {
	if x != nil {
		return x.Epistemic
	}
	return nil
}

func (x *Definition) GetModelConfig() *ModelConfig {
	if x != nil {
		return x.ModelConfig
	}
	return nil
}

// Condition message
type Condition struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Field    string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Operator string                 `protobuf:"bytes,2,opt,name=operator,proto3" json:"operator,omitempty"`
	// Types that are valid to be assigned to Value:
	//
	//	*Condition_NumberValue
	//	*Condition_StringValue
	//	*Condition_BoolValue
	Value         isCondition_Value `protobuf_oneof:"value"`
	FieldPath     string            `protobuf:"bytes,6,opt,name=fieldPath,proto3" json:"fieldPath,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Condition) Reset() {
	*x = Condition{}
	mi := &file_objectweaver_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Condition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Condition) ProtoMessage() {}

func (x *Condition) ProtoReflect() protoreflect.Message {
	mi := &file_objectweaver_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Condition.ProtoReflect.Descriptor instead.
func (*Condition) Descriptor() ([]byte, []int) {
	return file_objectweaver_proto_rawDescGZIP(), []int{1}
}

func (x *Condition) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *Condition) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *Condition) GetValue() isCondition_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Condition) GetNumberValue() float64 {
	if x != nil {
		if x, ok := x.Value.(*Condition_NumberValue); ok {
			return x.NumberValue
		}
	}
	return 0
}

func (x *Condition) GetStringValue() string {
	if x != nil {
		if x, ok := x.Value.(*Condition_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *Condition) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Value.(*Condition_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *Condition) GetFieldPath() string {
	if x != nil {
		return x.FieldPath
	}
	return ""
}

type isCondition_Value interface {
	isCondition_Value()
}

type Condition_NumberValue struct {
	NumberValue float64 `protobuf:"fixed64,3,opt,name=number_value,json=numberValue,proto3,oneof"`
}

type Condition_StringValue struct {
	StringValue string `protobuf:"bytes,4,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type Condition_BoolValue struct {
	BoolValue bool `protobuf:"varint,5,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

func (*Condition_NumberValue) isCondition_Value() {}

func (*Condition_StringValue) isCondition_Value() {}

func (*Condition_BoolValue) isCondition_Value() {}

// ConditionalBranch message
type ConditionalBranch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Conditions    []*Condition           `protobuf:"bytes,2,rep,name=conditions,proto3" json:"conditions,omitempty"`
	Logic         *Definition            `protobuf:"bytes,3,opt,name=logic,proto3" json:"logic,omitempty"`
	Then          *Definition            `protobuf:"bytes,4,opt,name=then,proto3" json:"then,omitempty"`
	Priority      int32                  `protobuf:"varint,5,opt,name=priority,proto3" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConditionalBranch) Reset() {
	*x = ConditionalBranch{}
	mi := &file_objectweaver_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConditionalBranch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConditionalBranch) ProtoMessage() {}

func (x *ConditionalBranch) ProtoReflect() protoreflect.Message {
	mi := &file_objectweaver_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConditionalBranch.ProtoReflect.Descriptor instead.
func (*ConditionalBranch) Descriptor() ([]byte, []int) {
	return file_objectweaver_proto_rawDescGZIP(), []int{2}
}

func (x *ConditionalBranch) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ConditionalBranch) GetConditions() []*Condition {
	if x != nil {
		return x.Conditions
	}
	return nil
}

func (x *ConditionalBranch) GetLogic() *Definition {
	if x != nil {
		return x.Logic
	}
	return nil
}

func (x *ConditionalBranch) GetThen() *Definition {
	if x != nil {
		return x.Then
	}
	return nil
}

func (x *ConditionalBranch) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

// DecisionPoint message
type DecisionPoint struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Name             string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	EvaluationPrompt string                 `protobuf:"bytes,2,opt,name=evaluationPrompt,proto3" json:"evaluationPrompt,omitempty"`
	Branches         []*ConditionalBranch   `protobuf:"bytes,3,rep,name=branches,proto3" json:"branches,omitempty"`
	Strategy         string                 `protobuf:"bytes,4,opt,name=strategy,proto3" json:"strategy,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DecisionPoint) Reset() {
	*x = DecisionPoint{}
	mi := &file_objectweaver_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecisionPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecisionPoint) ProtoMessage() {}

func (x *DecisionPoint) ProtoReflect() protoreflect.Message {
	mi := &file_objectweaver_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecisionPoint.ProtoReflect.Descriptor instead.
func (*DecisionPoint) Descriptor() ([]byte, []int) {
	return file_objectweaver_proto_rawDescGZIP(), []int{3}
}

func (x *DecisionPoint) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DecisionPoint) GetEvaluationPrompt() string {
	if x != nil {
		return x.EvaluationPrompt
	}
	return ""
}

func (x *DecisionPoint) GetBranches() []*ConditionalBranch {
	if x != nil {
		return x.Branches
	}
	return nil
}

func (x *DecisionPoint) GetStrategy() string {
	if x != nil {
		return x.Strategy
	}
	return ""
}

// EpistemicValidation message
type EpistemicValidation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Active        bool                   `protobuf:"varint,1,opt,name=active,proto3" json:"active,omitempty"`
	Judges        int32                  `protobuf:"varint,2,opt,name=judges,proto3" json:"judges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EpistemicValidation) Reset() {
	*x = EpistemicValidation{}
	mi := &file_objectweaver_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EpistemicValidation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EpistemicValidation) ProtoMessage() {}

func (x *EpistemicValidation) ProtoReflect() protoreflect.Message {
	mi := &file_objectweaver_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EpistemicValidation.ProtoReflect.Descriptor instead.
func (*EpistemicValidation) Descriptor() ([]byte, []int) {
	return file_objectweaver_proto_rawDescGZIP(), []int{4}
}

func (x *EpistemicValidation) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *EpistemicValidation) GetJudges() int32 {
	if x != nil {
		return x.Judges
	}
	return 0
}

// Focus message
type Focus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prompt        string                 `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Fields        []string               `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty"`
	KeepOriginal  bool                   `protobuf:"varint,3,opt,name=keepOriginal,proto3" json:"keepOriginal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Focus) Reset() {
	*x = Focus{}
	mi := &file_objectweaver_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Focus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Focus) ProtoMessage() {}

func (x *Focus) ProtoReflect() protoreflect.Message {
	mi := &file_objectweaver_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Focus.ProtoReflect.Descriptor instead.
func (*Focus) Descriptor() ([]byte, []int) {
	return file_objectweaver_proto_rawDescGZIP(), []int{5}
}

func (x *Focus) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *Focus) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *Focus) GetKeepOriginal() bool {
	if x != nil {
		return x.KeepOriginal
	}
	return false
}

// HashMap message
type HashMap struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	KeyInstruction  string                 `protobuf:"bytes,1,opt,name=keyInstruction,proto3" json:"keyInstruction,omitempty"`
	FieldDefinition *Definition            `protobuf:"bytes,2,opt,name=fieldDefinition,proto3" json:"fieldDefinition,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HashMap) Reset() {
	*x = HashMap{}
	mi := &file_objectweaver_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HashMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HashMap) ProtoMessage() {}

func (x *HashMap) ProtoReflect() protoreflect.Message {
	mi := &file_objectweaver_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HashMap.ProtoReflect.Descriptor instead.
func (*HashMap) Descriptor() ([]byte, []int) {
	return file_objectweaver_proto_rawDescGZIP(), []int{6}
}

func (x *HashMap) GetKeyInstruction() string {
	if x != nil {
		return x.KeyInstruction
	}
	return ""
}

func (x *HashMap) GetFieldDefinition() *Definition {
	if x != nil {
		return x.FieldDefinition
	}
	return nil
}

// Image message
type Image struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	Size          string                 `protobuf:"bytes,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Image) Reset() {
	*x = Image{}
	mi := &file_objectweaver_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Image) ProtoMessage() {}

func (x *Image) ProtoReflect() protoreflect.Message {
	mi := &file_objectweaver_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Image.ProtoReflect.Descriptor instead.
func (*Image) Descriptor() ([]byte, []int) {
	return file_objectweaver_proto_rawDescGZIP(), []int{7}
}

func (x *Image) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Image) GetSize() string {
	if x != nil {
		return x.Size
	}
	return ""
}

// ModelConfig message
type ModelConfig struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	MaxCompletionTokens int32                  `protobuf:"varint,1,opt,name=maxCompletionTokens,proto3" json:"maxCompletionTokens,omitempty"`
	Temperature         float32                `protobuf:"fixed32,2,opt,name=temperature,proto3" json:"temperature,omitempty"`
	TopP                float32                `protobuf:"fixed32,3,opt,name=topP,proto3" json:"topP,omitempty"`
	N                   int32                  `protobuf:"varint,4,opt,name=n,proto3" json:"n,omitempty"`
	Stream              bool                   `protobuf:"varint,5,opt,name=stream,proto3" json:"stream,omitempty"`
	Stop                []string               `protobuf:"bytes,6,rep,name=stop,proto3" json:"stop,omitempty"`
	PresencePenalty     float32                `protobuf:"fixed32,7,opt,name=presencePenalty,proto3" json:"presencePenalty,omitempty"`
	Seed                int32                  `protobuf:"varint,8,opt,name=seed,proto3" json:"seed,omitempty"`
	FrequencyPenalty    float32                `protobuf:"fixed32,9,opt,name=frequencyPenalty,proto3" json:"frequencyPenalty,omitempty"`
	LogitBias           map[string]int32       `protobuf:"bytes,10,rep,name=logitBias,proto3" json:"logitBias,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	LogProbs            bool                   `protobuf:"varint,11,opt,name=logProbs,proto3" json:"logProbs,omitempty"`
	TopLogProbs         int32                  `protobuf:"varint,12,opt,name=topLogProbs,proto3" json:"topLogProbs,omitempty"`
	User                string                 `protobuf:"bytes,13,opt,name=user,proto3" json:"user,omitempty"`
	Store               bool                   `protobuf:"varint,14,opt,name=store,proto3" json:"store,omitempty"`
	ReasoningEffort     string                 `protobuf:"bytes,15,opt,name=reasoningEffort,proto3" json:"reasoningEffort,omitempty"`
	Metadata            map[string]string      `protobuf:"bytes,16,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ChatTemplateKwargs  *structpb.Struct       `protobuf:"bytes,17,opt,name=chatTemplateKwargs,proto3" json:"chatTemplateKwargs,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ModelConfig) Reset() {
	*x = ModelConfig{}
	mi := &file_objectweaver_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelConfig) ProtoMessage() {}

func (x *ModelConfig) ProtoReflect() protoreflect.Message {
	mi := &file_objectweaver_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelConfig.ProtoReflect.Descriptor instead.
func (*ModelConfig) Descriptor() ([]byte, []int) {
	return file_objectweaver_proto_rawDescGZIP(), []int{8}
}

func (x *ModelConfig) GetMaxCompletionTokens() int32 {
	if x != nil {
		return x.MaxCompletionTokens
	}
	return 0
}

func (x *ModelConfig) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *ModelConfig) GetTopP() float32 {
	if x != nil {
		return x.TopP
	}
	return 0
}

func (x *ModelConfig) GetN() int32 {
	if x != nil {
		return x.N
	}
	return 0
}

func (x *ModelConfig) GetStream() bool {
	if x != nil {
		return x.Stream
	}
	return false
}

func (x *ModelConfig) GetStop() []string {
	if x != nil {
		return x.Stop
	}
	return nil
}

func (x *ModelConfig) GetPresencePenalty() float32 {
	if x != nil {
		return x.PresencePenalty
	}
	return 0
}

func (x *ModelConfig) GetSeed() int32 {
	if x != nil {
		return x.Seed
	}
	return 0
}

func (x *ModelConfig) GetFrequencyPenalty() float32 {
	if x != nil {
		return x.FrequencyPenalty
	}
	return 0
}

func (x *ModelConfig) GetLogitBias() map[string]int32 {
	if x != nil {
		return x.LogitBias
	}
	return nil
}

func (x *ModelConfig) GetLogProbs() bool {
	if x != nil {
		return x.LogProbs
	}
	return false
}

func (x *ModelConfig) GetTopLogProbs() int32 {
	if x != nil {
		return x.TopLogProbs
	}
	return 0
}

func (x *ModelConfig) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *ModelConfig) GetStore() bool {
	if x != nil {
		return x.Store
	}
	return false
}

func (x *ModelConfig) GetReasoningEffort() string {
	if x != nil {
		return x.ReasoningEffort
	}
	return ""
}

func (x *ModelConfig) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ModelConfig) GetChatTemplateKwargs() *structpb.Struct {
	if x != nil {
		return x.ChatTemplateKwargs
	}
	return nil
}

// RecursiveLoop message
type RecursiveLoop struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	MaxIterations           int32                  `protobuf:"varint,1,opt,name=maxIterations,proto3" json:"maxIterations,omitempty"`
	Selection               string                 `protobuf:"bytes,2,opt,name=selection,proto3" json:"selection,omitempty"`
	TerminationPoint        *DecisionPoint         `protobuf:"bytes,3,opt,name=terminationPoint,proto3" json:"terminationPoint,omitempty"`
	FeedbackPrompt          string                 `protobuf:"bytes,4,opt,name=feedbackPrompt,proto3" json:"feedbackPrompt,omitempty"`
	IncludePreviousAttempts bool                   `protobuf:"varint,5,opt,name=includePreviousAttempts,proto3" json:"includePreviousAttempts,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *RecursiveLoop) Reset() {
	*x = RecursiveLoop{}
	mi := &file_objectweaver_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecursiveLoop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecursiveLoop) ProtoMessage() {}

func (x *RecursiveLoop) ProtoReflect() protoreflect.Message {
	mi := &file_objectweaver_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecursiveLoop.ProtoReflect.Descriptor instead.
func (*RecursiveLoop) Descriptor() ([]byte, []int) {
	return file_objectweaver_proto_rawDescGZIP(), []int{9}
}

func (x *RecursiveLoop) GetMaxIterations() int32 {
	if x != nil {
		return x.MaxIterations
	}
	return 0
}

func (x *RecursiveLoop) GetSelection() string {
	if x != nil {
		return x.Selection
	}
	return ""
}

func (x *RecursiveLoop) GetTerminationPoint() *DecisionPoint {
	if x != nil {
		return x.TerminationPoint
	}
	return nil
}

func (x *RecursiveLoop) GetFeedbackPrompt() string {
	if x != nil {
		return x.FeedbackPrompt
	}
	return ""
}

func (x *RecursiveLoop) GetIncludePreviousAttempts() bool {
	if x != nil {
		return x.IncludePreviousAttempts
	}
	return false
}

// RequestBody message
type RequestBody struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prompt        string                 `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Definition    *Definition            `protobuf:"bytes,2,opt,name=definition,proto3" json:"definition,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestBody) Reset() {
	*x = RequestBody{}
	mi := &file_objectweaver_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestBody) ProtoMessage() {}

func (x *RequestBody) ProtoReflect() protoreflect.Message {
	mi := &file_objectweaver_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestBody.ProtoReflect.Descriptor instead.
func (*RequestBody) Descriptor() ([]byte, []int) {
	return file_objectweaver_proto_rawDescGZIP(), []int{10}
}

func (x *RequestBody) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *RequestBody) GetDefinition() *Definition {
	if x != nil {
		return x.Definition
	}
	return nil
}

// RequestFormat message
type RequestFormat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body          *structpb.Struct       `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	Authorization string                 `protobuf:"bytes,5,opt,name=authorization,proto3" json:"authorization,omitempty"`
	RequireFields []string               `protobuf:"bytes,6,rep,name=requireFields,proto3" json:"requireFields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestFormat) Reset() {
	*x = RequestFormat{}
	mi := &file_objectweaver_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestFormat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestFormat) ProtoMessage() {}

func (x *RequestFormat) ProtoReflect() protoreflect.Message {
	mi := &file_objectweaver_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestFormat.ProtoReflect.Descriptor instead.
func (*RequestFormat) Descriptor() ([]byte, []int) {
	return file_objectweaver_proto_rawDescGZIP(), []int{11}
}

func (x *RequestFormat) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *RequestFormat) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *RequestFormat) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *RequestFormat) GetBody() *structpb.Struct {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *RequestFormat) GetAuthorization() string {
	if x != nil {
		return x.Authorization
	}
	return ""
}

func (x *RequestFormat) GetRequireFields() []string {
	if x != nil {
		return x.RequireFields
	}
	return nil
}

// Response message
type Response struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Data          *structpb.Struct          `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	UsdCost       float64                   `protobuf:"fixed64,2,opt,name=usdCost,proto3" json:"usdCost,omitempty"`
	DetailedData  map[string]*DetailedField `protobuf:"bytes,3,rep,name=detailedData,proto3" json:"detailedData,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_objectweaver_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_objectweaver_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_objectweaver_proto_rawDescGZIP(), []int{12}
}

func (x *Response) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Response) GetUsdCost() float64 {
	if x != nil {
		return x.UsdCost
	}
	return 0
}

func (x *Response) GetDetailedData() map[string]*DetailedField {
	if x != nil {
		return x.DetailedData
	}
	return nil
}

// ScoreScale message
type ScoreScale struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Min           int32                  `protobuf:"varint,1,opt,name=min,proto3" json:"min,omitempty"`
	Max           int32                  `protobuf:"varint,2,opt,name=max,proto3" json:"max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScoreScale) Reset() {
	*x = ScoreScale{}
	mi := &file_objectweaver_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoreScale) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoreScale) ProtoMessage() {}

func (x *ScoreScale) ProtoReflect() protoreflect.Message {
	mi := &file_objectweaver_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoreScale.ProtoReflect.Descriptor instead.
func (*ScoreScale) Descriptor() ([]byte, []int) {
	return file_objectweaver_proto_rawDescGZIP(), []int{13}
}

func (x *ScoreScale) GetMin() int32 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *ScoreScale) GetMax() int32 {
	if x != nil {
		return x.Max
	}
	return 0
}

// ScoringCriteria message
type ScoringCriteria struct {
	state             protoimpl.MessageState       `protogen:"open.v1"`
	Dimensions        map[string]*ScoringDimension `protobuf:"bytes,1,rep,name=dimensions,proto3" json:"dimensions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	EvaluationModel   string                       `protobuf:"bytes,2,opt,name=evaluationModel,proto3" json:"evaluationModel,omitempty"`
	AggregationMethod string                       `protobuf:"bytes,3,opt,name=aggregationMethod,proto3" json:"aggregationMethod,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ScoringCriteria) Reset() {
	*x = ScoringCriteria{}
	mi := &file_objectweaver_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoringCriteria) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoringCriteria) ProtoMessage() {}

func (x *ScoringCriteria) ProtoReflect() protoreflect.Message {
	mi := &file_objectweaver_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoringCriteria.ProtoReflect.Descriptor instead.
func (*ScoringCriteria) Descriptor() ([]byte, []int) {
	return file_objectweaver_proto_rawDescGZIP(), []int{14}
}

func (x *ScoringCriteria) GetDimensions() map[string]*ScoringDimension {
	if x != nil {
		return x.Dimensions
	}
	return nil
}

func (x *ScoringCriteria) GetEvaluationModel() string {
	if x != nil {
		return x.EvaluationModel
	}
	return ""
}

func (x *ScoringCriteria) GetAggregationMethod() string {
	if x != nil {
		return x.AggregationMethod
	}
	return ""
}

// ScoringDimension message
type ScoringDimension struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Description   string                 `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	Scale         *ScoreScale            `protobuf:"bytes,2,opt,name=scale,proto3" json:"scale,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Weight        float64                `protobuf:"fixed64,4,opt,name=weight,proto3" json:"weight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScoringDimension) Reset() {
	*x = ScoringDimension{}
	mi := &file_objectweaver_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoringDimension) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoringDimension) ProtoMessage() {}

func (x *ScoringDimension) ProtoReflect() protoreflect.Message {
	mi := &file_objectweaver_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoringDimension.ProtoReflect.Descriptor instead.
func (*ScoringDimension) Descriptor() ([]byte, []int) {
	return file_objectweaver_proto_rawDescGZIP(), []int{15}
}

func (x *ScoringDimension) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ScoringDimension) GetScale() *ScoreScale {
	if x != nil {
		return x.Scale
	}
	return nil
}

func (x *ScoringDimension) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ScoringDimension) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

// SendImage message
type SendImage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImagesData    [][]byte               `protobuf:"bytes,1,rep,name=imagesData,proto3" json:"imagesData,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendImage) Reset() {
	*x = SendImage{}
	mi := &file_objectweaver_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendImage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendImage) ProtoMessage() {}

func (x *SendImage) ProtoReflect() protoreflect.Message {
	mi := &file_objectweaver_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendImage.ProtoReflect.Descriptor instead.
func (*SendImage) Descriptor() ([]byte, []int) {
	return file_objectweaver_proto_rawDescGZIP(), []int{16}
}

func (x *SendImage) GetImagesData() [][]byte {
	if x != nil {
		return x.ImagesData
	}
	return nil
}

// SpeechToText message
type SpeechToText struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Model             string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	AudioToTranscribe []byte                 `protobuf:"bytes,2,opt,name=audioToTranscribe,proto3" json:"audioToTranscribe,omitempty"`
	Language          string                 `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"`
	Format            string                 `protobuf:"bytes,4,opt,name=format,proto3" json:"format,omitempty"`
	ToString          bool                   `protobuf:"varint,5,opt,name=toString,proto3" json:"toString,omitempty"`
	ToCaptions        bool                   `protobuf:"varint,6,opt,name=toCaptions,proto3" json:"toCaptions,omitempty"`
	ChunkingStrategy  string                 `protobuf:"bytes,7,opt,name=chunkingStrategy,proto3" json:"chunkingStrategy,omitempty"`
	ExtraBody         *structpb.Struct       `protobuf:"bytes,8,opt,name=extraBody,proto3" json:"extraBody,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SpeechToText) Reset() {
	*x = SpeechToText{}
	mi := &file_objectweaver_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpeechToText) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpeechToText) ProtoMessage() {}

func (x *SpeechToText) ProtoReflect() protoreflect.Message {
	mi := &file_objectweaver_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpeechToText.ProtoReflect.Descriptor instead.
func (*SpeechToText) Descriptor() ([]byte, []int) {
	return file_objectweaver_proto_rawDescGZIP(), []int{17}
}

func (x *SpeechToText) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *SpeechToText) GetAudioToTranscribe() []byte {
	if x != nil {
		return x.AudioToTranscribe
	}
	return nil
}

func (x *SpeechToText) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *SpeechToText) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *SpeechToText) GetToString() bool {
	if x != nil {
		return x.ToString
	}
	return false
}

func (x *SpeechToText) GetToCaptions() bool {
	if x != nil {
		return x.ToCaptions
	}
	return false
}

func (x *SpeechToText) GetChunkingStrategy() string {
	if x != nil {
		return x.ChunkingStrategy
	}
	return ""
}

func (x *SpeechToText) GetExtraBody() *structpb.Struct {
	if x != nil {
		return x.ExtraBody
	}
	return nil
}

// SubordinateFunction message
type SubordinateFunction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Definition    *Definition            `protobuf:"bytes,2,opt,name=definition,proto3" json:"definition,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubordinateFunction) Reset() {
	*x = SubordinateFunction{}
	mi := &file_objectweaver_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubordinateFunction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubordinateFunction) ProtoMessage() {}

func (x *SubordinateFunction) ProtoReflect() protoreflect.Message {
	mi := &file_objectweaver_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubordinateFunction.ProtoReflect.Descriptor instead.
func (*SubordinateFunction) Descriptor() ([]byte, []int) {
	return file_objectweaver_proto_rawDescGZIP(), []int{18}
}

func (x *SubordinateFunction) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SubordinateFunction) GetDefinition() *Definition {
	if x != nil {
		return x.Definition
	}
	return nil
}

// TextToSpeech message
type TextToSpeech struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	StringToAudio string                 `protobuf:"bytes,2,opt,name=stringToAudio,proto3" json:"stringToAudio,omitempty"`
	Voice         string                 `protobuf:"bytes,3,opt,name=voice,proto3" json:"voice,omitempty"`
	Format        string                 `protobuf:"bytes,4,opt,name=format,proto3" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextToSpeech) Reset() {
	*x = TextToSpeech{}
	mi := &file_objectweaver_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextToSpeech) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextToSpeech) ProtoMessage() {}

func (x *TextToSpeech) ProtoReflect() protoreflect.Message {
	mi := &file_objectweaver_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextToSpeech.ProtoReflect.Descriptor instead.
func (*TextToSpeech) Descriptor() ([]byte, []int) {
	return file_objectweaver_proto_rawDescGZIP(), []int{19}
}

func (x *TextToSpeech) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *TextToSpeech) GetStringToAudio() string {
	if x != nil {
		return x.StringToAudio
	}
	return ""
}

func (x *TextToSpeech) GetVoice() string {
	if x != nil {
		return x.Voice
	}
	return ""
}

func (x *TextToSpeech) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

// Choice message for epistemic validation results
type Choice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Score         int32                  `protobuf:"varint,1,opt,name=score,proto3" json:"score,omitempty"`
	Confidence    float64                `protobuf:"fixed64,2,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Value         *structpb.Struct       `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Embedding     []float64              `protobuf:"fixed64,4,rep,packed,name=embedding,proto3" json:"embedding,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Choice) Reset() {
	*x = Choice{}
	mi := &file_objectweaver_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Choice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Choice) ProtoMessage() {}

func (x *Choice) ProtoReflect() protoreflect.Message {
	mi := &file_objectweaver_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Choice.ProtoReflect.Descriptor instead.
func (*Choice) Descriptor() ([]byte, []int) {
	return file_objectweaver_proto_rawDescGZIP(), []int{20}
}

func (x *Choice) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *Choice) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *Choice) GetValue() *structpb.Struct {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Choice) GetEmbedding() []float64 {
	if x != nil {
		return x.Embedding
	}
	return nil
}

// FieldMetadata contains metadata for a single field
type FieldMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokensUsed    int32                  `protobuf:"varint,1,opt,name=tokensUsed,proto3" json:"tokensUsed,omitempty"`
	Cost          float64                `protobuf:"fixed64,2,opt,name=cost,proto3" json:"cost,omitempty"`
	ModelUsed     string                 `protobuf:"bytes,3,opt,name=modelUsed,proto3" json:"modelUsed,omitempty"`
	Choices       []*Choice              `protobuf:"bytes,4,rep,name=choices,proto3" json:"choices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldMetadata) Reset() {
	*x = FieldMetadata{}
	mi := &file_objectweaver_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldMetadata) ProtoMessage() {}

func (x *FieldMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_objectweaver_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldMetadata.ProtoReflect.Descriptor instead.
func (*FieldMetadata) Descriptor() ([]byte, []int) {
	return file_objectweaver_proto_rawDescGZIP(), []int{21}
}

func (x *FieldMetadata) GetTokensUsed() int32 {
	if x != nil {
		return x.TokensUsed
	}
	return 0
}

func (x *FieldMetadata) GetCost() float64 {
	if x != nil {
		return x.Cost
	}
	return 0
}

func (x *FieldMetadata) GetModelUsed() string {
	if x != nil {
		return x.ModelUsed
	}
	return ""
}

func (x *FieldMetadata) GetChoices() []*Choice {
	if x != nil {
		return x.Choices
	}
	return nil
}

// DetailedField contains both the value and metadata for a field
type DetailedField struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *structpb.Struct       `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Metadata      *FieldMetadata         `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetailedField) Reset() {
	*x = DetailedField{}
	mi := &file_objectweaver_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetailedField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetailedField) ProtoMessage() {}

func (x *DetailedField) ProtoReflect() protoreflect.Message {
	mi := &file_objectweaver_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetailedField.ProtoReflect.Descriptor instead.
func (*DetailedField) Descriptor() ([]byte, []int) {
	return file_objectweaver_proto_rawDescGZIP(), []int{22}
}

func (x *DetailedField) GetValue() *structpb.Struct {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *DetailedField) GetMetadata() *FieldMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// StreamingResponse message for the stream method
type StreamingResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Data          *structpb.Struct          `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	UsdCost       float64                   `protobuf:"fixed64,2,opt,name=usdCost,proto3" json:"usdCost,omitempty"`
	Status        string                    `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	DetailedData  map[string]*DetailedField `protobuf:"bytes,4,rep,name=detailedData,proto3" json:"detailedData,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamingResponse) Reset() {
	*x = StreamingResponse{}
	mi := &file_objectweaver_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamingResponse) ProtoMessage() {}

func (x *StreamingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_objectweaver_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamingResponse.ProtoReflect.Descriptor instead.
func (*StreamingResponse) Descriptor() ([]byte, []int) {
	return file_objectweaver_proto_rawDescGZIP(), []int{23}
}

func (x *StreamingResponse) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *StreamingResponse) GetUsdCost() float64 {
	if x != nil {
		return x.UsdCost
	}
	return 0
}

func (x *StreamingResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *StreamingResponse) GetDetailedData() map[string]*DetailedField {
	if x != nil {
		return x.DetailedData
	}
	return nil
}

var File_objectweaver_proto protoreflect.FileDescriptor

const file_objectweaver_proto_rawDesc = "" +
	"\n" +
	"\x12objectweaver.proto\x12\n" +
	"jsonSchema\x1a\x1cgoogle/protobuf/struct.proto\"\xa1\t\n" +
	"\n" +
	"Definition\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12 \n" +
	"\vinstruction\x18\x02 \x01(\tR\vinstruction\x12F\n" +
	"\n" +
	"properties\x18\x03 \x03(\v2&.jsonSchema.Definition.PropertiesEntryR\n" +
	"properties\x12,\n" +
	"\x05items\x18\x04 \x01(\v2\x16.jsonSchema.DefinitionR\x05items\x12\x14\n" +
	"\x05model\x18\x05 \x01(\tR\x05model\x12(\n" +
	"\x0fprocessingOrder\x18\x06 \x03(\tR\x0fprocessingOrder\x12\"\n" +
	"\fsystemPrompt\x18\a \x01(\tR\fsystemPrompt\x12-\n" +
	"\ahashMap\x18\b \x01(\v2\x13.jsonSchema.HashMapR\ahashMap\x12<\n" +
	"\ftextToSpeech\x18\t \x01(\v2\x18.jsonSchema.TextToSpeechR\ftextToSpeech\x12<\n" +
	"\fspeechToText\x18\n" +
	" \x01(\v2\x18.jsonSchema.SpeechToTextR\fspeechToText\x12'\n" +
	"\x05image\x18\v \x01(\v2\x11.jsonSchema.ImageR\x05image\x12+\n" +
	"\x03req\x18\f \x01(\v2\x19.jsonSchema.RequestFormatR\x03req\x123\n" +
	"\vnarrowFocus\x18\r \x01(\v2\x11.jsonSchema.FocusR\vnarrowFocus\x12\"\n" +
	"\fselectFields\x18\x0e \x03(\tR\fselectFields\x123\n" +
	"\tsendImage\x18\x0f \x01(\v2\x15.jsonSchema.SendImageR\tsendImage\x12\x16\n" +
	"\x06stream\x18\x10 \x01(\bR\x06stream\x12&\n" +
	"\x0eoverridePrompt\x18\x11 \x01(\tR\x0eoverridePrompt\x12\x1a\n" +
	"\bpriority\x18\x12 \x01(\x05R\bpriority\x12?\n" +
	"\rdecisionPoint\x18\x13 \x01(\v2\x19.jsonSchema.DecisionPointR\rdecisionPoint\x12E\n" +
	"\x0fscoringCriteria\x18\x14 \x01(\v2\x1b.jsonSchema.ScoringCriteriaR\x0fscoringCriteria\x12?\n" +
	"\rrecursiveLoop\x18\x15 \x01(\v2\x19.jsonSchema.RecursiveLoopR\rrecursiveLoop\x12=\n" +
	"\tepistemic\x18\x16 \x01(\v2\x1f.jsonSchema.EpistemicValidationR\tepistemic\x129\n" +
	"\vmodelConfig\x18\x17 \x01(\v2\x17.jsonSchema.ModelConfigR\vmodelConfig\x1aU\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.jsonSchema.DefinitionR\x05value:\x028\x01\"\xcf\x01\n" +
	"\tCondition\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x1a\n" +
	"\boperator\x18\x02 \x01(\tR\boperator\x12#\n" +
	"\fnumber_value\x18\x03 \x01(\x01H\x00R\vnumberValue\x12#\n" +
	"\fstring_value\x18\x04 \x01(\tH\x00R\vstringValue\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x05 \x01(\bH\x00R\tboolValue\x12\x1c\n" +
	"\tfieldPath\x18\x06 \x01(\tR\tfieldPathB\a\n" +
	"\x05value\"\xd4\x01\n" +
	"\x11ConditionalBranch\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x125\n" +
	"\n" +
	"conditions\x18\x02 \x03(\v2\x15.jsonSchema.ConditionR\n" +
	"conditions\x12,\n" +
	"\x05logic\x18\x03 \x01(\v2\x16.jsonSchema.DefinitionR\x05logic\x12*\n" +
	"\x04then\x18\x04 \x01(\v2\x16.jsonSchema.DefinitionR\x04then\x12\x1a\n" +
	"\bpriority\x18\x05 \x01(\x05R\bpriority\"\xa6\x01\n" +
	"\rDecisionPoint\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12*\n" +
	"\x10evaluationPrompt\x18\x02 \x01(\tR\x10evaluationPrompt\x129\n" +
	"\bbranches\x18\x03 \x03(\v2\x1d.jsonSchema.ConditionalBranchR\bbranches\x12\x1a\n" +
	"\bstrategy\x18\x04 \x01(\tR\bstrategy\"E\n" +
	"\x13EpistemicValidation\x12\x16\n" +
	"\x06active\x18\x01 \x01(\bR\x06active\x12\x16\n" +
	"\x06judges\x18\x02 \x01(\x05R\x06judges\"[\n" +
	"\x05Focus\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\tR\x06prompt\x12\x16\n" +
	"\x06fields\x18\x02 \x03(\tR\x06fields\x12\"\n" +
	"\fkeepOriginal\x18\x03 \x01(\bR\fkeepOriginal\"s\n" +
	"\aHashMap\x12&\n" +
	"\x0ekeyInstruction\x18\x01 \x01(\tR\x0ekeyInstruction\x12@\n" +
	"\x0ffieldDefinition\x18\x02 \x01(\v2\x16.jsonSchema.DefinitionR\x0ffieldDefinition\"1\n" +
	"\x05Image\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12\x12\n" +
	"\x04size\x18\x02 \x01(\tR\x04size\"\xf8\x05\n" +
	"\vModelConfig\x120\n" +
	"\x13maxCompletionTokens\x18\x01 \x01(\x05R\x13maxCompletionTokens\x12 \n" +
	"\vtemperature\x18\x02 \x01(\x02R\vtemperature\x12\x12\n" +
	"\x04topP\x18\x03 \x01(\x02R\x04topP\x12\f\n" +
	"\x01n\x18\x04 \x01(\x05R\x01n\x12\x16\n" +
	"\x06stream\x18\x05 \x01(\bR\x06stream\x12\x12\n" +
	"\x04stop\x18\x06 \x03(\tR\x04stop\x12(\n" +
	"\x0fpresencePenalty\x18\a \x01(\x02R\x0fpresencePenalty\x12\x12\n" +
	"\x04seed\x18\b \x01(\x05R\x04seed\x12*\n" +
	"\x10frequencyPenalty\x18\t \x01(\x02R\x10frequencyPenalty\x12D\n" +
	"\tlogitBias\x18\n" +
	" \x03(\v2&.jsonSchema.ModelConfig.LogitBiasEntryR\tlogitBias\x12\x1a\n" +
	"\blogProbs\x18\v \x01(\bR\blogProbs\x12 \n" +
	"\vtopLogProbs\x18\f \x01(\x05R\vtopLogProbs\x12\x12\n" +
	"\x04user\x18\r \x01(\tR\x04user\x12\x14\n" +
	"\x05store\x18\x0e \x01(\bR\x05store\x12(\n" +
	"\x0freasoningEffort\x18\x0f \x01(\tR\x0freasoningEffort\x12A\n" +
	"\bmetadata\x18\x10 \x03(\v2%.jsonSchema.ModelConfig.MetadataEntryR\bmetadata\x12G\n" +
	"\x12chatTemplateKwargs\x18\x11 \x01(\v2\x17.google.protobuf.StructR\x12chatTemplateKwargs\x1a<\n" +
	"\x0eLogitBiasEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xfc\x01\n" +
	"\rRecursiveLoop\x12$\n" +
	"\rmaxIterations\x18\x01 \x01(\x05R\rmaxIterations\x12\x1c\n" +
	"\tselection\x18\x02 \x01(\tR\tselection\x12E\n" +
	"\x10terminationPoint\x18\x03 \x01(\v2\x19.jsonSchema.DecisionPointR\x10terminationPoint\x12&\n" +
	"\x0efeedbackPrompt\x18\x04 \x01(\tR\x0efeedbackPrompt\x128\n" +
	"\x17includePreviousAttempts\x18\x05 \x01(\bR\x17includePreviousAttempts\"]\n" +
	"\vRequestBody\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\tR\x06prompt\x126\n" +
	"\n" +
	"definition\x18\x02 \x01(\v2\x16.jsonSchema.DefinitionR\n" +
	"definition\"\xb0\x02\n" +
	"\rRequestFormat\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12@\n" +
	"\aheaders\x18\x03 \x03(\v2&.jsonSchema.RequestFormat.HeadersEntryR\aheaders\x12+\n" +
	"\x04body\x18\x04 \x01(\v2\x17.google.protobuf.StructR\x04body\x12$\n" +
	"\rauthorization\x18\x05 \x01(\tR\rauthorization\x12$\n" +
	"\rrequireFields\x18\x06 \x03(\tR\rrequireFields\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf9\x01\n" +
	"\bResponse\x12+\n" +
	"\x04data\x18\x01 \x01(\v2\x17.google.protobuf.StructR\x04data\x12\x18\n" +
	"\ausdCost\x18\x02 \x01(\x01R\ausdCost\x12J\n" +
	"\fdetailedData\x18\x03 \x03(\v2&.jsonSchema.Response.DetailedDataEntryR\fdetailedData\x1aZ\n" +
	"\x11DetailedDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12/\n" +
	"\x05value\x18\x02 \x01(\v2\x19.jsonSchema.DetailedFieldR\x05value:\x028\x01\"0\n" +
	"\n" +
	"ScoreScale\x12\x10\n" +
	"\x03min\x18\x01 \x01(\x05R\x03min\x12\x10\n" +
	"\x03max\x18\x02 \x01(\x05R\x03max\"\x93\x02\n" +
	"\x0fScoringCriteria\x12K\n" +
	"\n" +
	"dimensions\x18\x01 \x03(\v2+.jsonSchema.ScoringCriteria.DimensionsEntryR\n" +
	"dimensions\x12(\n" +
	"\x0fevaluationModel\x18\x02 \x01(\tR\x0fevaluationModel\x12,\n" +
	"\x11aggregationMethod\x18\x03 \x01(\tR\x11aggregationMethod\x1a[\n" +
	"\x0fDimensionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x122\n" +
	"\x05value\x18\x02 \x01(\v2\x1c.jsonSchema.ScoringDimensionR\x05value:\x028\x01\"\x8e\x01\n" +
	"\x10ScoringDimension\x12 \n" +
	"\vdescription\x18\x01 \x01(\tR\vdescription\x12,\n" +
	"\x05scale\x18\x02 \x01(\v2\x16.jsonSchema.ScoreScaleR\x05scale\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x16\n" +
	"\x06weight\x18\x04 \x01(\x01R\x06weight\"+\n" +
	"\tSendImage\x12\x1e\n" +
	"\n" +
	"imagesData\x18\x01 \x03(\fR\n" +
	"imagesData\"\xa5\x02\n" +
	"\fSpeechToText\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12,\n" +
	"\x11audioToTranscribe\x18\x02 \x01(\fR\x11audioToTranscribe\x12\x1a\n" +
	"\blanguage\x18\x03 \x01(\tR\blanguage\x12\x16\n" +
	"\x06format\x18\x04 \x01(\tR\x06format\x12\x1a\n" +
	"\btoString\x18\x05 \x01(\bR\btoString\x12\x1e\n" +
	"\n" +
	"toCaptions\x18\x06 \x01(\bR\n" +
	"toCaptions\x12*\n" +
	"\x10chunkingStrategy\x18\a \x01(\tR\x10chunkingStrategy\x125\n" +
	"\textraBody\x18\b \x01(\v2\x17.google.protobuf.StructR\textraBody\"a\n" +
	"\x13SubordinateFunction\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x126\n" +
	"\n" +
	"definition\x18\x02 \x01(\v2\x16.jsonSchema.DefinitionR\n" +
	"definition\"x\n" +
	"\fTextToSpeech\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12$\n" +
	"\rstringToAudio\x18\x02 \x01(\tR\rstringToAudio\x12\x14\n" +
	"\x05voice\x18\x03 \x01(\tR\x05voice\x12\x16\n" +
	"\x06format\x18\x04 \x01(\tR\x06format\"\x8b\x01\n" +
	"\x06Choice\x12\x14\n" +
	"\x05score\x18\x01 \x01(\x05R\x05score\x12\x1e\n" +
	"\n" +
	"confidence\x18\x02 \x01(\x01R\n" +
	"confidence\x12-\n" +
	"\x05value\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x05value\x12\x1c\n" +
	"\tembedding\x18\x04 \x03(\x01R\tembedding\"\x8f\x01\n" +
	"\rFieldMetadata\x12\x1e\n" +
	"\n" +
	"tokensUsed\x18\x01 \x01(\x05R\n" +
	"tokensUsed\x12\x12\n" +
	"\x04cost\x18\x02 \x01(\x01R\x04cost\x12\x1c\n" +
	"\tmodelUsed\x18\x03 \x01(\tR\tmodelUsed\x12,\n" +
	"\achoices\x18\x04 \x03(\v2\x12.jsonSchema.ChoiceR\achoices\"u\n" +
	"\rDetailedField\x12-\n" +
	"\x05value\x18\x01 \x01(\v2\x17.google.protobuf.StructR\x05value\x125\n" +
	"\bmetadata\x18\x02 \x01(\v2\x19.jsonSchema.FieldMetadataR\bmetadata\"\xa3\x02\n" +
	"\x11StreamingResponse\x12+\n" +
	"\x04data\x18\x01 \x01(\v2\x17.google.protobuf.StructR\x04data\x12\x18\n" +
	"\ausdCost\x18\x02 \x01(\x01R\ausdCost\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12S\n" +
	"\fdetailedData\x18\x04 \x03(\v2/.jsonSchema.StreamingResponse.DetailedDataEntryR\fdetailedData\x1aZ\n" +
	"\x11DetailedDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12/\n" +
	"\x05value\x18\x02 \x01(\v2\x19.jsonSchema.DetailedFieldR\x05value:\x028\x012\xa8\x01\n" +
	"\x11JSONSchemaService\x12?\n" +
	"\x0eGenerateObject\x12\x17.jsonSchema.RequestBody\x1a\x14.jsonSchema.Response\x12R\n" +
	"\x16StreamGeneratedObjects\x12\x17.jsonSchema.RequestBody\x1a\x1d.jsonSchema.StreamingResponse0\x01B\bZ\x06./grpcb\x06proto3"

var (
	file_objectweaver_proto_rawDescOnce sync.Once
	file_objectweaver_proto_rawDescData []byte
)

func file_objectweaver_proto_rawDescGZIP() []byte {
	file_objectweaver_proto_rawDescOnce.Do(func() {
		file_objectweaver_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_objectweaver_proto_rawDesc), len(file_objectweaver_proto_rawDesc)))
	})
	return file_objectweaver_proto_rawDescData
}

var file_objectweaver_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_objectweaver_proto_goTypes = []any{
	(*Definition)(nil),          // 0: jsonSchema.Definition
	(*Condition)(nil),           // 1: jsonSchema.Condition
	(*ConditionalBranch)(nil),   // 2: jsonSchema.ConditionalBranch
	(*DecisionPoint)(nil),       // 3: jsonSchema.DecisionPoint
	(*EpistemicValidation)(nil), // 4: jsonSchema.EpistemicValidation
	(*Focus)(nil),               // 5: jsonSchema.Focus
	(*HashMap)(nil),             // 6: jsonSchema.HashMap
	(*Image)(nil),               // 7: jsonSchema.Image
	(*ModelConfig)(nil),         // 8: jsonSchema.ModelConfig
	(*RecursiveLoop)(nil),       // 9: jsonSchema.RecursiveLoop
	(*RequestBody)(nil),         // 10: jsonSchema.RequestBody
	(*RequestFormat)(nil),       // 11: jsonSchema.RequestFormat
	(*Response)(nil),            // 12: jsonSchema.Response
	(*ScoreScale)(nil),          // 13: jsonSchema.ScoreScale
	(*ScoringCriteria)(nil),     // 14: jsonSchema.ScoringCriteria
	(*ScoringDimension)(nil),    // 15: jsonSchema.ScoringDimension
	(*SendImage)(nil),           // 16: jsonSchema.SendImage
	(*SpeechToText)(nil),        // 17: jsonSchema.SpeechToText
	(*SubordinateFunction)(nil), // 18: jsonSchema.SubordinateFunction
	(*TextToSpeech)(nil),        // 19: jsonSchema.TextToSpeech
	(*Choice)(nil),              // 20: jsonSchema.Choice
	(*FieldMetadata)(nil),       // 21: jsonSchema.FieldMetadata
	(*DetailedField)(nil),       // 22: jsonSchema.DetailedField
	(*StreamingResponse)(nil),   // 23: jsonSchema.StreamingResponse
	nil,                         // 24: jsonSchema.Definition.PropertiesEntry
	nil,                         // 25: jsonSchema.ModelConfig.LogitBiasEntry
	nil,                         // 26: jsonSchema.ModelConfig.MetadataEntry
	nil,                         // 27: jsonSchema.RequestFormat.HeadersEntry
	nil,                         // 28: jsonSchema.Response.DetailedDataEntry
	nil,                         // 29: jsonSchema.ScoringCriteria.DimensionsEntry
	nil,                         // 30: jsonSchema.StreamingResponse.DetailedDataEntry
	(*structpb.Struct)(nil),     // 31: google.protobuf.Struct
}
var file_objectweaver_proto_depIdxs = []int32{
	24, // 0: jsonSchema.Definition.properties:type_name -> jsonSchema.Definition.PropertiesEntry
	0,  // 1: jsonSchema.Definition.items:type_name -> jsonSchema.Definition
	6,  // 2: jsonSchema.Definition.hashMap:type_name -> jsonSchema.HashMap
	19, // 3: jsonSchema.Definition.textToSpeech:type_name -> jsonSchema.TextToSpeech
	17, // 4: jsonSchema.Definition.speechToText:type_name -> jsonSchema.SpeechToText
	7,  // 5: jsonSchema.Definition.image:type_name -> jsonSchema.Image
	11, // 6: jsonSchema.Definition.req:type_name -> jsonSchema.RequestFormat
	5,  // 7: jsonSchema.Definition.narrowFocus:type_name -> jsonSchema.Focus
	16, // 8: jsonSchema.Definition.sendImage:type_name -> jsonSchema.SendImage
	3,  // 9: jsonSchema.Definition.decisionPoint:type_name -> jsonSchema.DecisionPoint
	14, // 10: jsonSchema.Definition.scoringCriteria:type_name -> jsonSchema.ScoringCriteria
	9,  // 11: jsonSchema.Definition.recursiveLoop:type_name -> jsonSchema.RecursiveLoop
	4,  // 12: jsonSchema.Definition.epistemic:type_name -> jsonSchema.EpistemicValidation
	8,  // 13: jsonSchema.Definition.modelConfig:type_name -> jsonSchema.ModelConfig
	1,  // 14: jsonSchema.ConditionalBranch.conditions:type_name -> jsonSchema.Condition
	0,  // 15: jsonSchema.ConditionalBranch.logic:type_name -> jsonSchema.Definition
	0,  // 16: jsonSchema.ConditionalBranch.then:type_name -> jsonSchema.Definition
	2,  // 17: jsonSchema.DecisionPoint.branches:type_name -> jsonSchema.ConditionalBranch
	0,  // 18: jsonSchema.HashMap.fieldDefinition:type_name -> jsonSchema.Definition
	25, // 19: jsonSchema.ModelConfig.logitBias:type_name -> jsonSchema.ModelConfig.LogitBiasEntry
	26, // 20: jsonSchema.ModelConfig.metadata:type_name -> jsonSchema.ModelConfig.MetadataEntry
	31, // 21: jsonSchema.ModelConfig.chatTemplateKwargs:type_name -> google.protobuf.Struct
	3,  // 22: jsonSchema.RecursiveLoop.terminationPoint:type_name -> jsonSchema.DecisionPoint
	0,  // 23: jsonSchema.RequestBody.definition:type_name -> jsonSchema.Definition
	27, // 24: jsonSchema.RequestFormat.headers:type_name -> jsonSchema.RequestFormat.HeadersEntry
	31, // 25: jsonSchema.RequestFormat.body:type_name -> google.protobuf.Struct
	31, // 26: jsonSchema.Response.data:type_name -> google.protobuf.Struct
	28, // 27: jsonSchema.Response.detailedData:type_name -> jsonSchema.Response.DetailedDataEntry
	29, // 28: jsonSchema.ScoringCriteria.dimensions:type_name -> jsonSchema.ScoringCriteria.DimensionsEntry
	13, // 29: jsonSchema.ScoringDimension.scale:type_name -> jsonSchema.ScoreScale
	31, // 30: jsonSchema.SpeechToText.extraBody:type_name -> google.protobuf.Struct
	0,  // 31: jsonSchema.SubordinateFunction.definition:type_name -> jsonSchema.Definition
	31, // 32: jsonSchema.Choice.value:type_name -> google.protobuf.Struct
	20, // 33: jsonSchema.FieldMetadata.choices:type_name -> jsonSchema.Choice
	31, // 34: jsonSchema.DetailedField.value:type_name -> google.protobuf.Struct
	21, // 35: jsonSchema.DetailedField.metadata:type_name -> jsonSchema.FieldMetadata
	31, // 36: jsonSchema.StreamingResponse.data:type_name -> google.protobuf.Struct
	30, // 37: jsonSchema.StreamingResponse.detailedData:type_name -> jsonSchema.StreamingResponse.DetailedDataEntry
	0,  // 38: jsonSchema.Definition.PropertiesEntry.value:type_name -> jsonSchema.Definition
	22, // 39: jsonSchema.Response.DetailedDataEntry.value:type_name -> jsonSchema.DetailedField
	15, // 40: jsonSchema.ScoringCriteria.DimensionsEntry.value:type_name -> jsonSchema.ScoringDimension
	22, // 41: jsonSchema.StreamingResponse.DetailedDataEntry.value:type_name -> jsonSchema.DetailedField
	10, // 42: jsonSchema.JSONSchemaService.GenerateObject:input_type -> jsonSchema.RequestBody
	10, // 43: jsonSchema.JSONSchemaService.StreamGeneratedObjects:input_type -> jsonSchema.RequestBody
	12, // 44: jsonSchema.JSONSchemaService.GenerateObject:output_type -> jsonSchema.Response
	23, // 45: jsonSchema.JSONSchemaService.StreamGeneratedObjects:output_type -> jsonSchema.StreamingResponse
	44, // [44:46] is the sub-list for method output_type
	42, // [42:44] is the sub-list for method input_type
	42, // [42:42] is the sub-list for extension type_name
	42, // [42:42] is the sub-list for extension extendee
	0,  // [0:42] is the sub-list for field type_name
}

func init() { file_objectweaver_proto_init() }
func file_objectweaver_proto_init() {
	if File_objectweaver_proto != nil {
		return
	}
	file_objectweaver_proto_msgTypes[1].OneofWrappers = []any{
		(*Condition_NumberValue)(nil),
		(*Condition_StringValue)(nil),
		(*Condition_BoolValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_objectweaver_proto_rawDesc), len(file_objectweaver_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_objectweaver_proto_goTypes,
		DependencyIndexes: file_objectweaver_proto_depIdxs,
		MessageInfos:      file_objectweaver_proto_msgTypes,
	}.Build()
	File_objectweaver_proto = out.File
	file_objectweaver_proto_goTypes = nil
	file_objectweaver_proto_depIdxs = nil
}
